name: CI

on:
  push:
    branche:  master 
    tag: v*

jobs:
  build: 
    name: deploy application
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        qmake $GITHUB_WORKSPACE/subtitleFixer.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
        mingw32-make.exe -f $GITHUB_WORKSPACE/../build-subtitleFixer-Desktop_Qt_5_15_0_MinGW_64_bit-Release/Makefile qmake_all
        mingw32-make.exe -j8
        qmake $GITHUB_WORKSPACE
